name: build
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag of image'
        required: false
        default: 'test'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-corss:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            toolchain: nightly
            output: realm
          - target: aarch64-unknown-linux-gnu
            toolchain: nightly
            output: realm
    steps:
      - uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          override: true
      - name: compile
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: realm-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.output }}
